name: words_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Veritabanı
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # Tarih formatlama
  intl: ^0.18.1 

  # İkonlar
  cupertino_icons: ^1.0.2
  lucide_icons: ^0.257.0
  flutter_tts: ^4.2.3
  flutter_launcher_icons: ^0.14.4
  shared_preferences: ^2.2.2
  provider: ^6.0.2

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/word_list.json

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
